# .goreleaser.yml
# Build customization
builds:
  - binary: authserver
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
    format: tar.gz
    replacements:
        amd64: 64-bit
        darwin: macOS

