apiVersion: v1
kind: Secret
metadata:
  name: {{ template "authserver.name" . }}
  labels:
    app: {{ template "authserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "authserver.jwt.publicKey":  |- 
    {{ required "A value for publicKey" .Values.publicKey }}
  "authserver.jwt.privateKey": |- 
    {{ required "A value for privateKey"  .Values.privateKey }}
  "authserver.oauth.configFile": |- 
    {{ required "A value for configFile" .Values.configFile }}
